// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hydraproto/ship.proto

package hydraproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ship struct {
	Shipname             string             `protobuf:"bytes,1,opt,name=shipname,proto3" json:"shipname,omitempty"`
	CaptainName          string             `protobuf:"bytes,2,opt,name=CaptainName,proto3" json:"CaptainName,omitempty"`
	Crew                 []*Ship_CrewMember `protobuf:"bytes,3,rep,name=Crew,proto3" json:"Crew,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}
func (*Ship) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e37aaa1d1eb00b, []int{0}
}

func (m *Ship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship.Unmarshal(m, b)
}
func (m *Ship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship.Marshal(b, m, deterministic)
}
func (m *Ship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship.Merge(m, src)
}
func (m *Ship) XXX_Size() int {
	return xxx_messageInfo_Ship.Size(m)
}
func (m *Ship) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship.DiscardUnknown(m)
}

var xxx_messageInfo_Ship proto.InternalMessageInfo

func (m *Ship) GetShipname() string {
	if m != nil {
		return m.Shipname
	}
	return ""
}

func (m *Ship) GetCaptainName() string {
	if m != nil {
		return m.CaptainName
	}
	return ""
}

func (m *Ship) GetCrew() []*Ship_CrewMember {
	if m != nil {
		return m.Crew
	}
	return nil
}

type Ship_CrewMember struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecClearance         int32    `protobuf:"varint,3,opt,name=secClearance,proto3" json:"secClearance,omitempty"`
	Position             string   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ship_CrewMember) Reset()         { *m = Ship_CrewMember{} }
func (m *Ship_CrewMember) String() string { return proto.CompactTextString(m) }
func (*Ship_CrewMember) ProtoMessage()    {}
func (*Ship_CrewMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8e37aaa1d1eb00b, []int{0, 0}
}

func (m *Ship_CrewMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship_CrewMember.Unmarshal(m, b)
}
func (m *Ship_CrewMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship_CrewMember.Marshal(b, m, deterministic)
}
func (m *Ship_CrewMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship_CrewMember.Merge(m, src)
}
func (m *Ship_CrewMember) XXX_Size() int {
	return xxx_messageInfo_Ship_CrewMember.Size(m)
}
func (m *Ship_CrewMember) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship_CrewMember.DiscardUnknown(m)
}

var xxx_messageInfo_Ship_CrewMember proto.InternalMessageInfo

func (m *Ship_CrewMember) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ship_CrewMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship_CrewMember) GetSecClearance() int32 {
	if m != nil {
		return m.SecClearance
	}
	return 0
}

func (m *Ship_CrewMember) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func init() {
	proto.RegisterType((*Ship)(nil), "hydraproto.Ship")
	proto.RegisterType((*Ship_CrewMember)(nil), "hydraproto.Ship.CrewMember")
}

func init() {
	proto.RegisterFile("hydraproto/ship.proto", fileDescriptor_b8e37aaa1d1eb00b)
}

var fileDescriptor_b8e37aaa1d1eb00b = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x8a, 0x83, 0x30,
	0x18, 0x84, 0x51, 0xb3, 0xcb, 0xee, 0xef, 0xb2, 0x87, 0x1f, 0x0a, 0xc1, 0x5e, 0xc4, 0x93, 0xa7,
	0x08, 0xed, 0x23, 0x78, 0x6e, 0x0f, 0xf6, 0x09, 0xa2, 0x06, 0x0c, 0xd4, 0x24, 0x44, 0xa1, 0xf4,
	0x89, 0xfb, 0x1a, 0x25, 0x7f, 0x69, 0xd3, 0xde, 0xfe, 0xf9, 0x66, 0xc8, 0x64, 0x60, 0x33, 0x5d,
	0x47, 0x2f, 0x9d, 0xb7, 0xab, 0x6d, 0x96, 0x49, 0x3b, 0x41, 0x27, 0x42, 0xc4, 0xd5, 0x2d, 0x01,
	0x76, 0x9a, 0xb4, 0xc3, 0x02, 0x7e, 0x42, 0xc4, 0xc8, 0x59, 0xf1, 0xa4, 0x4c, 0xea, 0xdf, 0xee,
	0xa5, 0xb1, 0x84, 0xbc, 0x95, 0x6e, 0x95, 0xda, 0x1c, 0x83, 0x9d, 0x92, 0xfd, 0x8e, 0xb0, 0x01,
	0xd6, 0x7a, 0x75, 0xe1, 0x59, 0x99, 0xd5, 0xf9, 0x6e, 0x2b, 0x62, 0x83, 0x08, 0xaf, 0x8b, 0x60,
	0x1e, 0xd4, 0xdc, 0x2b, 0xdf, 0x51, 0xb0, 0x70, 0x00, 0x91, 0xe1, 0x3f, 0xa4, 0x7a, 0xa4, 0xda,
	0xaf, 0x2e, 0xd5, 0x23, 0x22, 0x30, 0x13, 0x9b, 0xe8, 0xc6, 0x0a, 0xfe, 0x16, 0x35, 0xb4, 0x67,
	0x25, 0xbd, 0x34, 0x83, 0xe2, 0x19, 0xa5, 0x3f, 0x58, 0x18, 0xe1, 0xec, 0xa2, 0x57, 0x6d, 0x0d,
	0x67, 0x8f, 0x11, 0x4f, 0xdd, 0x7f, 0xd3, 0x77, 0xf6, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe,
	0xe3, 0x5c, 0xc5, 0x15, 0x01, 0x00, 0x00,
}
